### ISSUE TITLE
Installation Fails on Mac OS

### ISSUE THREAD

**Issue by IIKiiNGsLYII** [steinerd/Loupedeck.AudioSwitcherPlugin#4]
**Version**

**Submitting a...**

[ ] Bug report
[ ] Feature request

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Other information:**

**Comment by steinerd** [comment]
This will never be a MacOS application. It uses the Windows SDK to change audio devices on Windows only.
